### ISSUE TITLE
Change types as per new convention

### ISSUE THREAD

**Issue by gautam-e** [mojodojodev/mojodojo.dev#12]
We need to change the code as per: https://docs.modular.com/mojo/changelog.html#changed

**Comment by mojodojodev** [comment]
Good call all changed thanks

**Comment by gautam-e** [comment]
Hey @mojodojodev I think you did a find and replace over all the files and that's created some mistakes like: 

> So we use Int32 instead of Int32, similarly using Float32 instead of Float32. Closes Issue #152.

I think it needs to be done more selectively like in the the guides only, or something like that.

**Comment by mojodojodev** [comment]
Whoops! I think that was the only one (mentioning old syntax with new change), did a quick run through and looks all clear. Thanks again!

**Comment by gautam-e** [comment]
Ok that's good then! Cheers.
