### ISSUE TITLE
[Bugs] Some user interface elements do not work in the mobile version

### ISSUE THREAD

**Issue by AxelThePop** [mojodojodev/mojodojo.dev#22]
While browsing this site using the Safari browser for iOS, I found some bugs:
"search icon" not working
"hamburger menu" not working
"toggle color mode" not working 

Phone: iPhone 6. iOS Version: 12.5.7

**Comment by mojodojodev** [comment]
Hi @AxelThePop I'm really sorry but the static site generator I'm using to enable those features make heavy use of browser features that are enabled from iOS 14 onward, so the minimum hardware to use them would be an iPhone 7, unfortunately iPhone 6 is capped at iOS 12.
