### ISSUE TITLE
RSS-Feed: pubData gets updated

### ISSUE THREAD

**Issue by jdlib** [mojodojodev/mojodojo.dev#25]
A RSS-Feed is available from https://mojodojo.dev/rss.xml:
The pubDate of items seems to be set to the current date from time to time, with the effect that items get republished:
Example from current rss.xml:
```
   <item>
      <title>Why Use Mojo?</title>
      <link>https://www.mojodojo.dev/blog/2023-05-08-why-use-mojo.html</link>
      <guid>https://www.mojodojo.dev/blog/2023-05-08-why-use-mojo.html</guid>
      <source url="https://www.mojodojo.dev/rss.xml">Why Use Mojo?</source>
      <description>The Mojo toolchain is not yet available, but you can signup (https://www.modular.com/get-started) to get early preview access to a Mojo notebook. Check the official why mojo pag...</description>
  !!! <pubDate>Sun, 18 Jun 2023 11:48:48 GMT</pubDate>
      ...

```

**Comment by mojodojodev** [comment]
Thanks for raising I'll look into it

**Comment by mojodojodev** [comment]
Thanks so much for raising this, looks like I had the dates in the wrong format:

![image](https://github.com/mojodojodev/mojodojo.dev/assets/132558431/477d98f7-4ae0-4829-be73-5cbdee50f909)

**Comment by jdlib** [comment]
Great, thanks a lot.
