### ISSUE TITLE
Feature Request: Sort by latest, or a Latest Changes page.

### ISSUE THREAD

**Issue by elliotwaite** [mojodojodev/mojodojo.dev#3]
I like to stay up to date on the latest additions to the Mojo Team Answers page, but currently, it's hard to do that from the website, so I come to this repo to look through the latest commits.

This made me think that maybe a feature could be added to the Mojo Team Answers page that allowed you to sort them by the date they were added. Or you could add something like a "Latest Changes" page that was like a changelog for the website.

Just an idea. Thanks for collecting and organizing all this useful information.

**Comment by mojodojodev** [comment]
Hi @elliotwaite thanks for your interest, and I'm a huge fan of `CHANGELOG.md`'s so yes I'll definitely dedicate a page to this, thanks for the suggestion.

**Comment by elliotwaite** [comment]
Nice, thanks.

**Comment by mojodojodev** [comment]
Done thanks, you can see it now at https://mojodojo.dev/updates

**Comment by elliotwaite** [comment]
Sweet 😃, looks great. And thanks for the shoutout!

Another idea I thought of that you might be interested in is starting a weekly newsletter for "This week in Mojo". I've seen this done for [Rust](https://this-week-in-rust.org/) ([twitter](https://twitter.com/ThisWeekInRust)) and [React](https://thisweekinreact.com/) ([twitter](https://twitter.com/sebastienlorber)). It could help you build an audience to promote any Mojo Dojo content, and you could generate revenue by including sponsored content in the emails (you can check out [a newsletter from This Week in React](https://thisweekinreact.com/newsletter/145) for an example of the type of sponsored content you could include). And once you're generating some revenue from it, you could potentially just use a portion of that revenue to pay someone else to write it for you and you could just review it or something.

I'm not sure if this fits in with your long-term goals for Mojo Dojo, but it seems like it could be a win-win for you and the Mojo community.

**Comment by mojodojodev** [comment]
Oh yeah I love `this week in Rust` that's another great idea thanks

**Comment by elliotwaite** [comment]
Cool, glad you like it.
