### ISSUE TITLE
Mojo Team Answers sometimes misleads with name of source

### ISSUE THREAD

**Issue by gryznar** [mojodojodev/mojodojo.dev#33]
In current week, there is a entry called  "Using async fn". Source of it looks like that:

2023-07-08 Github Alex Kirchhoff

But  this links points to Discord discussion, so it will be much better if it will have "Discord discussion" or sth like that in its text.

There are a lot of other  wrong sources but I am not sure if  its general rule, that all  Discord sources have wrong name

**Comment by mojodojodev** [comment]
I did a regex search and found quite a few of these, thanks for raising!

Fixed now.
