### ISSUE TITLE
[Content] Writing contents on StringLiteral and StringRef

### ISSUE THREAD

**Issue by Lorenzobattistela** [mojodojodev/mojodojo.dev#36]
I know this is work in progress, and I'm looking forward to contribute with this so we can build a great learning environment on Mojo. That said, I think we can add the builtins for stringliteral and ref (https://docs.modular.com/mojo/MojoBuiltin/StringRef.html) (https://docs.modular.com/mojo/MojoBuiltin/StringLiteral.html). You can assign me for this. Thanks and great work

**Comment by mojodojodev** [comment]
Great thanks Lorenzo much appreciated
